---
dns_bind_packages:
  - bind
  - bind-utils

dns_service_name: "named"
dns_named_conf_path: "/etc/named.conf"
dns_zone_dir: "/var/named"
dns_zone_file: "{{ dns_zone_name }}.zone"
dns_reverse_zone_file: "{{ dns_reverse_zone_name }}.zone"

dns_zone_name: "example.internal"
dns_reverse_zone_name: "0.168.192.in-addr.arpa"
dns_zone_serial: "2026010101"

dns_ns_fqdn: "ns1.{{ dns_zone_name }}"
dns_admin_rname: "admin.{{ dns_zone_name }}"

dns_listen_on_ipv4:
  - "127.0.0.1"

dns_allow_query:
  - "localhost"

dns_recursion: false
dns_forwarders: []

dns_ttl: 3600
dns_refresh: 3600
dns_retry: 900
dns_expire: 1209600
dns_minimum_ttl: 3600

dns_a_records:
  - name: "ns1"
    ip: "192.168.0.10"
